### ISSUE TITLE
Now the font in the book becomes bigger, how to change it to be small ?

### ISSUE THREAD

**Issue by zbhuang** [xiaoweiChen/Cpp_Concurrency_In_Action#6]
Hi Xiaowei, 
Thanks for your hard work.
Two days ago, I downloaded pdf file, and it was 368 pages long. And Today I found you update the preface, and I download pdf file, and found it now it is 569 pages. 
I wonder where to make the change so that people can download the file with small number of pages (so that it can be printed out) ?
Thanks.

**Comment by xiaoweiChen** [comment]
Hi zbHuang,

Glad to see your words.

I guess you download this book form gitbook, and I have not notice the page number of pdf file.
And I know you meaning, when my network is not well, download the book form gitbook is a time consuming thing.

For your question, I have no good idea, the pdf is generated automatically. And I not recommend read this translated book by pdf, because of the Chinese support is not very well, you will see some fonts mix in your downloaded pdf file.

Finally,  I recommend you read this book online, you can get the latest update and no need waiting for downloading pdf file in this way.

PS. I see your pull request. I am busy working these days. And Thanks you like this book.
